import Head from 'next/head'
import Image from 'next/image'

import Link from 'next/link';
import Logo from '../public/logo.jpg';
import Navbar from '../components/Navbar';
import TestButton from '../components/TestButton';
export default function Home() {


  return (
    <div className={""}>
      <Head>
        <title>MBTI Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={"container mx-auto lg:px-16 md:px-12 sm:px-4 px-4 my-12"}>
        <div className={"grid md:grid-cols-2 gap-6 mb-20"}>
          <div className={"flex flex-col mt-6"}>
            <div className={""}>
              <h1 className={"text-6xl mb-6"}>
                Бидний бэлтгэсэн Тест
              </h1>
              <h4 className={"text-1xl"}>
                Бид уг тестийг сайн дураараа хийсэн болно. Мэдээж бусад тесттэй адилхан mistype хийгдэх асуудал гарахыг үгүйсгүй. Тиймэрхүү асуудал болгон дээр бид нар хариуцлага хүлээхгүй болохыг мэдэгдэе.
              </h4>
              <div className={"w-40 mt-6"}>
                <Link href="/test">
                  <a>  <TestButton /></a>
                </Link>
              </div>

            </div>
          </div>
          <div className={"flex justify-center"}>
            <div>
              <Image className={"rounded-full"} alt="MBTI Mongolia Logo big" src={Logo} width={400} height={400} />
            </div>
          </div>
        </div>
        <div>
          Бидний тухай
        </div>

      </main>


      <footer className={""}>

      </footer>
    </div>
  )
}
